version: '3'
services:
  db:
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie
      TZ: UTC
      TZDATA: UTC
      PGTZ: UTC